frase = 'Curso em Vídeo Python'
print (frase[1:15])
print (len(frase))
print (frase.count('o'))
print (frase.find('deo'))
print (frase.replace('Python', 'Android'))
print (frase.upper())
print (frase.lower())
print (frase.capitalize())
print (frase.title())

dividido = frase.split()
print (dividido)
print (dividido[2])
print (dividido[2][3])
print ('-'.join(dividido))