n = input ('Digite algo: ')
print (f'O tipo primitivo desse valor é {type(n)}')
print (f'Só tem espaços? {n.isspace()}')
print (f'E é um número? {n.isnumeric()}')
print (f'E é alfabetico? {n.isalpha()}')
print (f'E é alfanumerico? {n.isalnum()}')
print (f'E está em maiúsculas? {n.isupper()}')
print (f'E está em minúsculas? {n.islower()}')
print (f'E está capitalizada? {n.istitle()}')